name: gomeat
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used  as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+1

environment:
  sdk: '>=3.1.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter  


  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
#  cupertino_icons: ^1.0.2
#  pinput: 1.2.0
  font_awesome_flutter: 10.5.0
  carousel_slider: 4.2.1
  dots_indicator: 3.0.0
  material_design_icons_flutter: 7.0.7296
  badges: 3.1.1
  animated_bottom_navigation_bar: 1.2.0
  table_calendar: 3.0.9
  flutter_phoenix: 1.1.1
  flutter_barcode_scanner: ^2.0.0
  provider: any
  shimmer: ^3.0.0
  connectivity_plus: 4.0.2
  dio: 5.3.2
  firebase_analytics: ^10.4.5
  firebase_auth: ^4.8.0
  firebase_core: ^2.15.1
  mobile_number: ^2.1.1
#  otp_autofill: 2.1.0
  sms_autofill: 2.3.0
  flutter_facebook_auth: ^6.0.1
  google_sign_in: ^6.1.4
  cached_network_image: ^3.2.3
  geocoding: ^2.1.0
  firebase_messaging: 14.6.7
  flutter_paystack: ^1.0.7
  photo_view: ^0.14.0
  url_launcher: ^6.1.12
  shared_preferences: ^2.2.0
  permission_handler: ^10.4.3
  image_picker: ^1.0.2
  image_cropper: ^5.0.0
  flutter_image_compress: ^2.0.4
  email_validator: ^2.0.1
  geolocator: ^10.0.0
  share_plus: 7.1.0
  flutter_html: ^3.0.0-beta.2
  flutter_rating_bar: 4.0.1
  google_maps_flutter: ^2.4.0
  flutter_mapbox_autocomplete: ^2.0.0
  mapbox_search: ^3.2.0
  flutter_polyline_points: ^2.0.0
  sign_in_with_apple: ^5.0.0
  flutter_local_notifications: ^15.1.1
  path_provider: ^2.1.0
  readmore: 2.2.0
  timelines: ^0.1.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.6
  marquee: ^2.2.0
  flutter_speed_dial: ^7.0.0
  # speed_dial_fab: ^2.1.1

dependency_overrides:
  intl: ^0.18.1
  http: ^1.0.0
  razorpay_flutter: ^1.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  generate: true
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/

  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: PoppinsMedium
      fonts:
        - asset: assets/fonts/Poppins-Medium.otf
    - family: PoppinsLight
      fonts:
        - asset: assets/fonts/Poppins-Light.otf  
    - family: PoppinsRegular
      fonts:
        - asset: assets/fonts/Poppins-Regular.otf               
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
